# Generated by Django 6.0 on 2025-12-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('check_in_time', models.IntegerField(blank=True, null=True)),
                ('check_out_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
